// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD89UcwWPT2zls9lIBxKVK39VGKqbA_iOc',
    appId: '1:503682889954:web:c3727fcc9fc147cf6306bb',
    messagingSenderId: '503682889954',
    projectId: 'yumapp123',
    authDomain: 'yumapp123.firebaseapp.com',
    storageBucket: 'yumapp123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJf7NIwwTpGsTNoIPU2hxrqHbp-Rd7s88',
    appId: '1:503682889954:android:229893dd51fb67fb6306bb',
    messagingSenderId: '503682889954',
    projectId: 'yumapp123',
    storageBucket: 'yumapp123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAARz_NxYpXTrMUb5Ff4uoF04FzygS1G3A',
    appId: '1:503682889954:ios:6ae532204aac90a56306bb',
    messagingSenderId: '503682889954',
    projectId: 'yumapp123',
    storageBucket: 'yumapp123.appspot.com',
    iosClientId: '503682889954-87me5ip7dbsilvdq6k8c1uu5b5n3brsf.apps.googleusercontent.com',
    iosBundleId: 'com.annaraczynska.yumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAARz_NxYpXTrMUb5Ff4uoF04FzygS1G3A',
    appId: '1:503682889954:ios:6ae532204aac90a56306bb',
    messagingSenderId: '503682889954',
    projectId: 'yumapp123',
    storageBucket: 'yumapp123.appspot.com',
    iosClientId: '503682889954-87me5ip7dbsilvdq6k8c1uu5b5n3brsf.apps.googleusercontent.com',
    iosBundleId: 'com.annaraczynska.yumApp',
  );
}
